export interface ICountry {
    id: number,
    name: string,
}

export const listOfCountries = [
    {id: 1, name: "Alabama"},
    {id: 2, name: "Algeria"},
    {id: 3, name: "Andorra"},
    {id: 4, name: "Argentina"},
    {id: 5, name: "Bangladesh"},
    {id: 6, name: "Belize"},
    {id: 7, name: "Burundi"},
    {id: 8, name: "Chile"},
    {id: 9, name: "China"},
    {id: 10, name: "Colombia"},
    {id: 11, name: "Gambia"},
    {id: 12, name: "Haiti"},
    {id: 13, name: "Jamaica"},
    {id: 14, name: "Liberia"},
    {id: 15, name: "Lithuania"},
    {id: 16, name: "Montenegro"},
    {id: 17, name: "Nauru"},
    {id: 18, name: "Norway"},
    {id: 19, name: "Russia"},
    {id: 20, name: "Thailand"},
    {id: 21, name: "Ukraine"},
    {id: 22, name: "Vanuatu"},
    {id: 23, name: "Venezuela"},
    {id: 24, name: "Yemen"},
    {id: 25, name: "Zambia"},
    {id: 26, name: "Zimbabwe"},
    {id: 27, name: "Sudan"},
    {id: 28, name: "Nepal"},
    {id: 29, name: "Mongolia"},
    {id: 30, name: "Kiribati"},
] as ICountry[];